import './globals.scss';
import '../styles/header.scss';
import '../styles/introduction.scss';
import '../styles/propertiesList.scss';
import '../styles/addPropertySection.scss';

export const metadata = {
    title: 'Rent Manager',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body>{children}</body>
        </html>
    );
}
